Petcard/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    email = db.Column(db.String(100))
    password = db.Column(db.String(100))
    data_created = db.Column(db.DateTime(timezone=True), default=func.now()) 
    pet = db.relationship('Petcard', backref='user', passive_deletes=  True)


class Petcard(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    image = db.Column(db.Text, unique=True, nullable=False)
    name = db.Column(db.String(100))
    birthday = db.Column(db.Date) 
    breed = db.Column(db.String(100))
    gender = db.Column(db.String(1))
    owner = db.Column(db.Integer, db.ForeignKey('user.id', ondelete="CASCADE"), nullable=False)
    mimetype = db.Column(db.Text, nullable=False)
    

Petcard/website/__init__.py
from flask import Flask 
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "helloworld"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'   
    db.init_app(app)
     
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    
    from .models import User, Petcard
    
    create_database(app)
    
    login_manager = LoginManager()
    login_manager.login_view = "auth.login"
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
        
    return app


def create_database(app):
    if not path.exists("website" + DB_NAME):
        db.create_all(app=app)

Petcard/website/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, session
from . import db 
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint("auth", __name__)

@auth.route("/", methods=['POST', 'GET'])
@auth.route("/login", methods=['POST', 'GET'])
def login():
    if request.method == 'POST':
        email = request.form.get("email")
        password = request.form.get("password")
        
        user = User.query.filter_by(email=email).first()
        
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Password is incorrect.', category='error')
        else:
            flash('Email is incorrect.', category='error')
    
    return render_template("login.html", user=current_user)
    

@auth.route("/signin", methods=['POST', 'GET'])
def signin():
    if request.method == 'POST':
        username = request.form.get("username").title()
        email = request.form.get("email")
        password = request.form.get("password")
        passwordConfirm = request.form.get("passwordConfirm")
        
        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()
        
        if email_exists:
            flash('Email is already in use.', category='error')
        elif username_exists:
            flash('Username is already in use.', category='error')
        elif password != passwordConfirm:
            flash('Password don\'t match.', category='error')
        elif len(username) < 3:
            flash('Username is too short.', category='error')
        elif len(password) < 6:
            flash('Password is too short.', category='error')
        elif len(email) < 4:
            flash('Email is invalid.', category='error')            
        else:
            new_user = User(username=username, email=email, 
                            password=generate_password_hash(password, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash('User created!', category='sucess')
            return redirect(url_for('views.register'))
    
    return render_template("signin.html", user=current_user)
    
    
@auth.route("/logout")
@login_required
def logout():
    logout_user()
    session.pop('_flashes', None)
    return(redirect(url_for('auth.login')))

Petcard/website/views.py
import mimetypes
from flask import Blueprint, redirect, render_template, request, flash, url_for, Response
from flask_login import login_required, current_user
from .models import Petcard
from . import db
from datetime import date, datetime

views = Blueprint("views", __name__)

@views.route("/")
@views.route("/home")
@login_required
def home():
    petcard = Petcard.query.filter_by(owner=current_user.id).all()
    return render_template('home.html', user=current_user, petcard=petcard)


@views.route("/register", methods=["GET", "POST"])
@login_required
def register():
    format = "%Y-%m-%d"
    
    if request.method == "POST":
        name = request.form.get("name").title()
        image = request.files["image"]
        birthday = request.form.get("birthday")
        birthday = datetime.strptime(birthday, format).date()
        breed = request.form.get("breed")
        gender = request.form.get("gender")
        mimetype = image.mimetype
        
        if not name:
            flash("Name cannot be empty", category="error")
        elif not birthday:
            flash("Birthday cannot be empty", category="error")
        elif not breed:
            flash("Breed cannot be empty", category="error")
        elif not gender:
            flash("Gender cannot be empty", category="error")
        elif not image:
            flash("Image cannot be empty", category="error")
        
        else:
            petcard = Petcard(name=name, image=image.read(), birthday=birthday, breed=breed, 
                              gender=gender, owner=current_user.id, mimetype=mimetype)
            db.session.add(petcard)
            db.session.commit()
            flash("Petcard created!", category="sucess")
            return redirect(url_for("views.home"))
            
    return render_template('registerPet.html', user=current_user)


@views.route("/petcard/<int:id>/image")
def render_image(id):
    petcard = Petcard.query.filter_by(id=id).first()
    if not petcard:
        return 'No img with that id', 404
    return Response(petcard.image, mimetype=petcard.mimetype)


@views.route("/petcard/<int:id>/delete")
def delete_petcard(id):
    petcard = Petcard.query.filter_by(id=id).first()
    db.session.delete(petcard)
    db.session.commit()
    
    return redirect(url_for("views.home"))


@views.route("/petcard/<int:id>/edit",  methods=["GET", "POST"])
def edit_petcard(id):
    petcard = Petcard.query.filter_by(id=id).first()
    
    if request.method == "POST":
        format = "%Y-%m-%d"
        
        petcard.name = request.form.get("name").title()
        birthday = request.form.get("birthday")
        birthday = datetime.strptime(birthday, format).date()
        petcard.breed = request.form.get("breed")
        petcard.gender = request.form.get("gender")
        if request.files["image"]:
            petcard.image = request.files["image"].read()
            petcard.mimetype = request.files["image"].mimetype
        
        db.session.add(petcard)
        db.session.commit()
        return redirect(url_for("views.home"))
    
    return render_template('registerPet.html', user=current_user, petcard=petcard)

Petcard/website/templates/home.html
{% extends 'index.html' %}

{% block content %}
<h1 align="center">Your Pet</h1>
<div class="petlist" id="petcard">
    {% for pet in petcard %}
        <div class="card-pet">
            <div class="pet-image-div">
                <img class="pet-image" src="{{ url_for('views.render_image', id=pet.id)}}"/>
                <div class="pet-edit-delete">
                    <a href="{{ url_for('views.edit_petcard', id=pet.id) }}">
                        <span>
                            <img src={{ url_for('static', filename='edit.png') }} />
                        </span>
                    </a>
                    <a href="{{ url_for('views.delete_petcard', id=pet.id) }}">
                        <span>
                            <img src={{ url_for('static', filename='delete.png') }} />
                        </span>
                    </a>
                </div>
            </div>
            <div class="pet-content">
                <h5 class="card-title text-light"><strong>{{ pet.name }}</strong></h5>
                <h6 class="card-subtitle mb-2 text-light">{{ pet.user.username }}</h6>
                <h6 class="card-subtitle mb-2 text-light">{{ pet.breed }}</h6>
                <h6 class="card-subtitle mb-2 text-light">{{ 'Female' if pet.gender == 'F' else 'Male' }}</h6>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

Petcard/website/templates/index.html
<!DOCTYPE html>

<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8"/>
        <title>Petcard</title>
        <link rel="shortcut icon" type="image/ico" href={{ url_for('static', filename='favicon.ico') }}/>
        <link rel="stylesheet" href={{ url_for('static', filename='style.css') }}/>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous"/>
    </head>
    <body style="background: #9e87f7">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <button
                class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbar">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                <a class="nav-item nav-link" href="/home">Home</a>
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="/logout">Logout</a>
                  <a class="nav-item nav-link" href="/register">Register</a>
                {% else %}
                  <a class="nav-item nav-link" href="/login">Login</a>
                  <a class="nav-item nav-link" href="/signin">Sign In</a>
                {% endif %}
                </div>
              </div>
            </div>
          </nav>
        {% block content %}{% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
        crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js "></script>
    </body>
</html>
    

Petcard/website/templates/login.html
{% extends 'index.html' %}

{% block content %}
  <form class="box" action="#" method="post">
    <h1>Login</h1>
    <div class="message">
      {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>
      <input type="email" name="email" placeholder="Email"/>
      <input type="password" name="password" placeholder="Password"/>
      <input type="submit" name="" value="Login">
      <input type="button" onclick="location.href='/signin';" value="Sign in"/>
  </form>
{% endblock %}

Petcard/website/templates/registerPet.html
{% extends 'index.html' %}

{% block content %}
<form class="register" action="#" method="post", enctype="multipart/form-data">
    <h2>Register your pet</h2>

    <label class='send' for="image">Send file</label>
    <input type="file" name="image" id="image" onchange="previewFile(this);">
    {% if petcard %}
        <img class="file" id="previewImg" src="{{ url_for('views.render_image', id=petcard.id)}}" 
        alt="Placeholder">
        <input type="text" name="name" placeholder="Name" value="{{ petcard.name }}">
        <input type="date" name="birthday" value="{{ petcard.birthday }}">
        <input type="text" name="breed" placeholder="Breed" value="{{ petcard.breed }}">
        <div class="gender">
            <div class="form-check form-check-inline">
                <label class="form-check-label" for="inlineRadio1">F</label>
                {% if petcard.gender == "F" %}
                    <input class="form-check-input" type="radio" name="gender" 
                    id="inlineRadio1" value="F" checked>
                {% else %}
                    <input class="form-check-input" type="radio" name="gender" 
                    id="inlineRadio1" value="F">
                {% endif %}
            </div>
            <div class="form-check form-check-inline">
                <label class="form-check-label" for="inlineRadio2">M</label>
                {% if petcard.gender == "M" %}
                    <input class="form-check-input" type="radio" name="gender" 
                    id="inlineRadio2" value="M" checked>
                {% else %}
                    <input class="form-check-input" type="radio" name="gender" 
                    id="inlineRadio2" value="M">
                {% endif %}
            </div>
        </div>
    {% else %}
        <img class="file" id="previewImg" src={{ url_for('static', filename='notfound.png')}}
        alt="Placeholder">
        <input type="text" name="name" placeholder="Name">
        <input type="date" name="birthday">
        <input type="text" name="breed" placeholder="Breed">
        <div class="gender">
            <div class="form-check form-check-inline">
                <label class="form-check-label" for="inlineRadio1">F</label>
                <input class="form-check-input" type="radio" name="gender" 
                id="inlineRadio1" value="F">
            </div>
            <div class="form-check form-check-inline">
                <label class="form-check-label" for="inlineRadio2">M</label>
                <input class="form-check-input" type="radio" name="gender" 
                id="inlineRadio2" value="M">
            </div>
        </div>
    {% endif %}
    <input type="submit" name="register" value="Register">
</form>
<script>
    function previewFile(input){
        var file = $("input[type=file]").get(0).files[0];
 
        if(file){
            var reader = new FileReader();
 
            reader.onload = function(){
                $("#previewImg").attr("src", reader.result);
            }
            reader.readAsDataURL(file);
        }
    }
</script>
{% endblock %}

Petcard/website/templates/signin.html
{% extends 'index.html' %}

{% block content %}
  <form class="box" action="#" method="post">
    <h1>Login</h1>
    <div class="message">
      {% with messages = get_flashed_messages() %}
          {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
          {% endif %}
        {% endwith %}
    </div>
    <input type="text" name="username" placeholder="Name"/>
    <input type="email" name="email" placeholder="Email"/>
    <input type="password" name="password" placeholder="Password"/>
    <input type="password" name="passwordConfirm" placeholder="Confirm Password"/>
    <input type="submit" name="signin" value="Sign in">
  </form>
{% endblock %}